# Generated by Django 6.0.2 on 2026-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
