# Generated by Django 6.0.2 on 2026-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='storage_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
